# Generated by Django 2.2 on 2020-10-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_devicereports_userreport_userreportreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='process_status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
