# Generated by Django 2.2 on 2020-10-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userreport_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereports',
            name='process_status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
