# Generated by Django 2.2 on 2020-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_devicereports_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='firestation',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='rescuecenter',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
