# Generated by Django 2.2 on 2020-10-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='user pics/pic.webp', null=True, upload_to='user pics'),
        ),
    ]
