# Generated by Django 2.2 on 2020-10-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201004_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicereports',
            name='process_status',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='process_status',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
