# Generated by Django 2.2 on 2020-10-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201004_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereports',
            name='oxygen',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
